type SnapshotDBKey = string;
type OriginDBKey = string;

export const SNAPSHOT_PROPERTY_MAP: Record<SnapshotDBKey, OriginDBKey> = {
	Date: 'Date',
	'Account Currency': 'Account Currency',
	'Account Value (Custom)': 'Account Value (Custom)',
	'Account Value (USD)': 'Account Value (USD)',
	Balance: 'Balance',
	'Balance (Custom)': 'Balance (Custom)',
	'Balance (USD)': 'Balance (USD)',
	'Display Exchange Rate': 'Display Exchange Rate',
	'Exchange Rate': 'Exchange Rate',
	'Exchange Source (Account → USD)': 'Exchange Source (Account → USD)',
	'Exchange Source (USD → Display)': 'Exchange Source (USD → Display)',
	'Financial Institution': 'Financial Institution',
	Inverted: 'Inverted',
	Loan: 'Loan',
	'Loan (Custom)': 'Loan (Custom)',
	'Loan (USD)': 'Loan (USD)',
	'Net Balance (Custom)': 'Net Balance (Custom)',
	'Net Balance (USD)': 'Net Balance (USD)',
	'Stock Market Value (Custom)': 'Stock Market Value (Custom)',
	'Stocks Market Value (USD)': 'Stocks Market Value (USD)',
	'Total Balance (Custom)': 'Total Balance (Custom)',
	'Total Balance (USD)': 'Total Balance (USD)',
	'Transaction Count': 'Transaction Count',
	'Transactions (General)': 'Transactions (General)',
	'Transactions(Investment)': 'Transactions(Investment)',
	Type: 'Type',
};
